// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCollection(arg1:string):Promise<main.Collection>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<main.CollectionItem>;

export function CreateRequest(arg1:string,arg2:string,arg3:string):Promise<main.CollectionItem>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteItem(arg1:string,arg2:string):Promise<void>;

export function GetAllCollections():Promise<Array<main.Collection>>;

export function GetCollection(arg1:string):Promise<main.Collection>;

export function MoveItem(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateCollection(arg1:string,arg2:string):Promise<main.Collection>;

export function UpdateItem(arg1:string,arg2:string,arg3:string,arg4:main.RequestData):Promise<main.CollectionItem>;
