// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseCollection(arg1) {
  return window['go']['main']['CollectionService']['CloseCollection'](arg1);
}

export function CreateCollection(arg1) {
  return window['go']['main']['CollectionService']['CreateCollection'](arg1);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['CollectionService']['CreateFolder'](arg1, arg2, arg3);
}

export function CreateRequest(arg1, arg2, arg3) {
  return window['go']['main']['CollectionService']['CreateRequest'](arg1, arg2, arg3);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['CollectionService']['DeleteCollection'](arg1);
}

export function DeleteItem(arg1, arg2) {
  return window['go']['main']['CollectionService']['DeleteItem'](arg1, arg2);
}

export function GetCollection(arg1) {
  return window['go']['main']['CollectionService']['GetCollection'](arg1);
}

export function GetOpenCollections() {
  return window['go']['main']['CollectionService']['GetOpenCollections']();
}

export function MoveItem(arg1, arg2, arg3) {
  return window['go']['main']['CollectionService']['MoveItem'](arg1, arg2, arg3);
}

export function OpenCollection() {
  return window['go']['main']['CollectionService']['OpenCollection']();
}

export function OpenCollectionFromPath(arg1) {
  return window['go']['main']['CollectionService']['OpenCollectionFromPath'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['CollectionService']['SetContext'](arg1);
}

export function UpdateCollection(arg1, arg2) {
  return window['go']['main']['CollectionService']['UpdateCollection'](arg1, arg2);
}

export function UpdateItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['CollectionService']['UpdateItem'](arg1, arg2, arg3, arg4);
}
