// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendRequest(arg1) {
  return window['go']['main']['HTTPClient']['SendRequest'](arg1);
}
